version: "3"

volumes:
  mysql-data:

services:
  
  database:
    image: mysql:latest
    container_name: preserve_database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: preserve@123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql